services:
  frontend:
    build: ./frontend
    volumes:
        - "./frontend:/app"
        - /app/node_modules
    ports:
        - "5173:5173"
    command: "yarn dev"
  backend:
    build: ./backend
    volumes:
        - "./backend:/app"
        - /app/node_modules
    ports:
        - "4000:4000"
    command: "yarn dev"